require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CirrusMD/podspecs.git'

platform :ios, '12.0'

target 'VbtCirrusmdBridgeLibraryExample' do
  use_frameworks!
  use_unimodules!
  pod 'CirrusMDSDK','~> 6.2.0'
  pod 'AwaitKit', '~> 5.2.0'
  pod 'PromiseKit', '~> 6.13.1'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

      pod 'react-native-vbt-cirrusmd-bridge-library', :path => '../..'
end
